/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as SwapIndexImport } from './routes/swap/index'
import { Route as OnboardingIndexImport } from './routes/onboarding/index'
import { Route as LaunchpadIndexImport } from './routes/launchpad/index'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const SwapIndexRoute = SwapIndexImport.update({
  id: '/swap/',
  path: '/swap/',
  getParentRoute: () => rootRoute,
} as any)

const OnboardingIndexRoute = OnboardingIndexImport.update({
  id: '/onboarding/',
  path: '/onboarding/',
  getParentRoute: () => rootRoute,
} as any)

const LaunchpadIndexRoute = LaunchpadIndexImport.update({
  id: '/launchpad/',
  path: '/launchpad/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/launchpad/': {
      id: '/launchpad/'
      path: '/launchpad'
      fullPath: '/launchpad'
      preLoaderRoute: typeof LaunchpadIndexImport
      parentRoute: typeof rootRoute
    }
    '/onboarding/': {
      id: '/onboarding/'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingIndexImport
      parentRoute: typeof rootRoute
    }
    '/swap/': {
      id: '/swap/'
      path: '/swap'
      fullPath: '/swap'
      preLoaderRoute: typeof SwapIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/launchpad': typeof LaunchpadIndexRoute
  '/onboarding': typeof OnboardingIndexRoute
  '/swap': typeof SwapIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/launchpad': typeof LaunchpadIndexRoute
  '/onboarding': typeof OnboardingIndexRoute
  '/swap': typeof SwapIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/launchpad/': typeof LaunchpadIndexRoute
  '/onboarding/': typeof OnboardingIndexRoute
  '/swap/': typeof SwapIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/launchpad' | '/onboarding' | '/swap'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/launchpad' | '/onboarding' | '/swap'
  id: '__root__' | '/' | '/launchpad/' | '/onboarding/' | '/swap/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LaunchpadIndexRoute: typeof LaunchpadIndexRoute
  OnboardingIndexRoute: typeof OnboardingIndexRoute
  SwapIndexRoute: typeof SwapIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LaunchpadIndexRoute: LaunchpadIndexRoute,
  OnboardingIndexRoute: OnboardingIndexRoute,
  SwapIndexRoute: SwapIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/launchpad/",
        "/onboarding/",
        "/swap/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/launchpad/": {
      "filePath": "launchpad/index.tsx"
    },
    "/onboarding/": {
      "filePath": "onboarding/index.tsx"
    },
    "/swap/": {
      "filePath": "swap/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
